version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dio
      MONGO_INITDB_ROOT_PASSWORD: dio
    networks: 
      - prod-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dio
      ME_CONFIG_MONGODB_ADMINPASSWORD: dio
      ME_CONFIG_MONGODB_URL: mongodb://dio:dio@mongo:27017/
    networks: 
      - prod-network

  web:
    build: .
    ports:
      - "8000:5000"
    networks: 
      - prod-network
  redis:
    image: "redis:alpine"


networks:
  prod-network:
    driver: bridge